# Generated by Django 4.2 on 2023-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TS', 'Tumbles'), ('VB', 'V Bar'), ('RC', 'Rop Cable'), ('YS', 'Yoga Sheet'), ('PB', 'Push Up Bar'), ('HG', 'Hand Grip'), ('IC', 'Ice-Cream')], max_length=2),
        ),
    ]
