# Generated by Django 4.2 on 2023-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, default='static/img/userprofile.jpg', null=True, upload_to='pro_pic/'),
        ),
    ]
