# Generated by Django 4.2 on 2023-05-26 05:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_rename_expiration_date_pricingplan_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricingPlan',
            new_name='Plan',
        ),
    ]
