# Generated by Django 4.2 on 2023-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='cancelable',
            field=models.BooleanField(default=True),
        ),
    ]
