# Generated by Django 4.2 on 2023-06-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_orderplaced_cancelable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='cancelable',
        ),
    ]
